config/routes.rb
Rails.application.routes.draw do

  get '/test' => 'exchanges#index'
  get '/index' => 'exchanges#index'
  get '/exchange' => 'exchanges#show'
  root "exchanges#index"
  resources :exchanges

end

app/models/exchange/exchange_query.rb
class ExchangeQuery < ActiveModel
  include ActiveModel::Validations
  attr_accessor :date, :amount, :from_curr, :to_curr, :result

  validates :amount, numericality: true
  validates :amount, presence: true
end

app/models/result.rb
class Result
	def initialize(value, rates_hash)
		@value = value
		@rates_hash = rates_hash
	end

	attr_reader :value, :rates_hash
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/exchanges_controller.rb
class ExchangesController < ApplicationController
  require 'exchange_service'
  require 'yaml'
  include ActionView::Helpers::NumberHelper

  def index
    @amount_error = session[:not_a_number]
    ExchangeService.new.currency_change(1, 'USD', 'USD')
    reset_session
  end

  def create
    # Load the names of the currencies from local file
    names_path = Rails.root.join("config", "currency_names.yml").to_s
    @currency_names = YAML.load_file(names_path)

    @date = params[:exchanges]['date']

    amount = params[:exchanges]['amount']
    @amount = sprintf('%.2f', amount.to_f)

    @from_curr = params[:exchanges]['from_curr']
    @to_curr = params[:exchanges]['to_curr']

    result = ExchangeService.new.currency_change(
        @date,
        @amount,
        @from_curr,
        @to_curr)  
    @value = result.value
    @rates = result.rates_hash

    # Check if the amount given is a number, 
    # if not, redirect back to index page with error message.
    # Otherwise, proceed as normal
    if @amount.to_f == 0.0
      not_a_number = "Amount must be a number"
      session[:not_a_number] = not_a_number
      redirect_to :index 
    else 
      render :show
    end
  end

  def show
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exchanges_helper.rb
module ExchangesHelper
end

app/views/exchanges/index.html.erb
<div class="container">
  <hr>
  <div class="row">
    <div class="header col-xs-12">
      <h1>Xchange Currency Converter</h1>
      <p>Tom's test project for FreeAgent</p>
    </div>
  </div>
  <hr>
  <div class="row intro">
    <p>This application uses exchange data from the <a href="http://www.ecb.europa.eu/stats/eurofxref/eurofxref-hist-90d.xml" target="blank" title="click here to view the raw exchange data">European Central Bank</a>. The ECB update this data once every weekday, so you can get the exchange rates for all the dates listed in the drop-down box below.</p>
  </div>
  <div class="row">
    <div class="form col-xs-12">
      <%= form_for :exchanges, url: exchanges_path do |f| %>
          <div class="date">
            <%= f.label :select_a_date %>
            <%= f.select(:date, $dates) %>
          </div>

          <p class="amount">
            <%= f.label :amount %><br>
            <%= f.text_field :amount %>
          </p>

          <h5 class="amount_error"><%= @amount_error %></h5>

          <div class="from">
            <%= f.label :from %>
            <%= f.select(:from_curr, $currencies) %>
          </div>

          <div class="to">
            <%= f.label :to %>
            <%= f.select(:to_curr, $currencies) %>
          </div>

          <p>
            <%= f.submit :convert %>
          </p>
      <% end %>
    </div>
  </div>
</div>

app/views/exchanges/show.html.erb
<div class="container">
  <hr>
  <div class="row">
    <div class="header col-xs-12">
      <h1><%= link_to 'Xchange Currency Converter', exchanges_path %></h1>
      <p>Tom's test project for FreeAgent</p>
    </div>
  </div>
  <hr>

  <div class="row">
    <div class="col-md-4 result">
      <h2><strong class="curr"><%= @amount %> <%= @from_curr %></strong></h2>
    </div>
    <div class="col-md-4 result">
      <h2><em>is equal to </em></h2>
    </div>
    <div class="col-md-4 result">
      <h2><strong class="curr"><%= @value %> <%= @to_curr %></strong></h2>
    </div>
  </div>

  <div class="row">
    <div style="text-align: center;" class="col-md-6 currency_name">
      <h5>
        <%= @from_curr %> = <%= @currency_names[@from_curr] %>
      </h5>
    </div>

    <div style="text-align: center;" class="col-md-6 currency_name">
      <h5>
        <%= @to_curr %> = <%= @currency_names[@to_curr] %>
      </h5>
    </div>
  </div>

  <hr>

  <div class="row">    
    <div style="text-align: center;" class="col-xs-12 currency_name">
      <h5>
        This is the exchange rate for the date you selected (<%= @date %>). A list of all the available currencies for that date is shown below.
      </h5>
    </div>
  </div>

  <div class="row">
    <div style="text-align: center;" class="col-lg-12 rates_table">
      <h5>
        <table>
          <tr>
            <th>Currency</th>
            <th>Rate</th>
            <th colspan="2"></th>
          </tr>

          <% @rates.each do |key, value| %>
          <tr>
            <td><%= key %></td>
            <td><%= value %></td>
          </tr>
          <% end %>
        </table>        
      </h5>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Xchange</title>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" charset="UTF-8">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
<%= yield %>
</body>
</html>